name: Build and Run SpecFlow
 
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set environment variables
        run: |
          echo "API_ENDPOINT=${{ secrets.API_ENDPOINT }}" >> $GITHUB_ENV
          echo "DHL_API_ENDPOINT=${{ secrets.DHL_API_ENDPOINT }}" >> $GITHUB_ENV
          echo "EASYPOST_TRACKING_ENDPOINT=${{ secrets.EASYPOST_TRACKING_ENDPOINT }}" >> $GITHUB_ENV
          echo "LANDMARK_API_ENDPOINT=${{ secrets.LANDMARK_API_ENDPOINT }}" >> $GITHUB_ENV
 
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'
 
      - name: Install dependencies
        run: |
          dotnet restore
          dotnet add package NUnit
          dotnet add package NUnit3TestAdapter
          dotnet add package Microsoft.NET.Test.Sdk
 
      - name: Run tests
        run: |
          dotnet test --logger "trx;LogFileName=test_results.trx"
 
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test_results.trx
 
      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test_results.trx
 
      - name: Publish test results to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./test-results
