name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET SDK
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    # Restore dependencies (important for ensuring the correct packages are used)
    - name: Restore dependencies
      run: dotnet restore

    # Build the project
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Run tests
    - name: Run tests
      run: dotnet test --configuration Release --no-build

    # Publish the project
    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./publish

    # Upload build artifacts (latest version)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ./publish

    # Optionally: Upload other files, like logs or additional artifacts
    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: ./logs

    # Clean up the build (optional but helps in long-running pipelines)
    - name: Clean up
      run: dotnet clean --configuration Release
